### ISSUE TITLE
We should have an abstract class describing all network elements

### ISSUE THREAD

**Issue by michalusio** [michalusio/PoProject#8]

**Comment by BarteeX** [comment]
Jakie elementy sieci będą po niej dziedziczyć? Co jest ogólne dla wszystkich elemntow sieci? [Wejscie, Przetworzenie Sygnału, Wyjscie... Co dalej?]

**Comment by michalusio** [comment]
Lista połączeń, z których każde ma jakąś maksymalną prędkość i rodzaj duplexu (Full/Half). Jeszcze może być ping łącza i procent błędów.
